#定义变量
variables:
  #定义克隆的路径  $CI_BUILDS_DIR 为 runners.builds_dir 设置的路径
  GIT_CLONE_PATH: $CI_BUILDS_DIR/rong-v2/theta-data-api

# 定义 stages
stages:
  - build
  - deploy

# 定义 job
build:
  stage: build
  variables:
    GIT_STRATEGY: fetch
  script:
    - npm ci
    - npm run build
  tags:
    - rong-v2
  only:
    - master

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none

  script:
#    - pm2 delete ecosystem.config.js
    - pm2 start ecosystem.config.js --env test
  tags:
    - rong-v2
  only:
    - master
